# Keycloak SSO Application Clients Configuration

realm: customer

# PKCE Client - Public client for web/mobile applications
pkce_client:
  client_id: webapp-pkce
  name: Web Application (PKCE)
  description: Public client using Authorization Code + PKCE flow for web and mobile apps
  enabled: true
  
  # Flow configurations
  flows:
    standard_flow: true           # Authorization Code Flow
    direct_access_grants: false   # Resource Owner Password Credentials
    implicit_flow: false           # Implicit Flow (deprecated)
    service_accounts: false        # Client Credentials Flow
  
  # PKCE settings
  pkce:
    enabled: true
    challenge_method: S256  # SHA-256
  
  # Redirect URIs
  redirect_uris:
    - http://localhost:5173/callback
  
  # CORS web origins - add all origins that will make requests to Keycloak
  web_origins:
    - http://localhost:5173


  # Token settings (in seconds)
  token_settings:
    access_token_lifespan: 300      # 5 minutes
    session_idle_timeout: 1800      # 30 minutes
    session_max_lifespan: 36000     # 10 hours
  
  # Additional settings
  consent_required: false
  display_on_consent_screen: true

# M2M Client - Confidential client for service-to-service communication
m2m_client:
  client_id: backend-service-m2m
  name: Backend Service (M2M)
  description: Confidential client using Client Credentials flow for machine-to-machine communication
  enabled: true
  
  # Flow configurations
  flows:
    standard_flow: false
    direct_access_grants: false
    implicit_flow: false
    service_accounts: true  # Enable Client Credentials Flow
  
  # Client secret (CHANGE THIS IN PRODUCTION!)
  client_secret: your-secure-client-secret-here-change-me-32chars
  
  # Token settings (in seconds)
  token_settings:
    access_token_lifespan: 3600  # 1 hour
  
  # Service account roles (optional)
  service_account_roles: []
    # - view-users
    # - manage-users
    # - query-groups

# Optional: Additional client scopes
custom_scopes:
  - name: webapp-custom-scope
    description: Custom scope for web application
    include_in_token_scope: true
    mappers:
      - name: user-groups-mapper
        type: user-attribute
        user_attribute: groups
        claim_name: groups
        claim_value_type: String
  
  - name: backend-custom-scope
    description: Custom scope for backend service
    include_in_token_scope: true
    mappers: []

# Protocol mappers
mappers:
  audience_mapper:
    enabled: true
    add_to_id_token: true
    add_to_access_token: true
